### PR TITLE
Skip OS-X build

### PR DESCRIPTION
**Pull request by bgruening**
- [ ] I have read the guidelines above.
- [ ] This PR adds a new recipe.
- [ ] This PR updates an existing recipe.
- [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by bgruening** [comment]
@cristhomas this one here :)

**Comment by cristhomas** [comment]
Sorry, I'm still learning GH =D

**Comment by bgruening** [comment]
No problem, this one will turn green at some point. Feel free to merge your PR then.
Thanks!

**Comment by cristhomas** [comment]
ok thanks!

**Pull request merged**
